Add grace period
pokt-foundation/rate-limiter pull request #14
Opened 2022-09-14 18:18 UTC by pablocampogo

Adds grace period feature for not showing apps as rate limited until certain hours passes
Apps that have never passed their limits are sent to the PHD endpoint to set the `FirstDateSurpassed` field

2022-09-14 20:48 UTC, adshmh requested changes

2022-09-14 20:48 UTC, adshmh commented on cache/cache.go
> +		count := int(relayCount.Count.Failure + relayCount.Count.Success)
We should only count successful relays.

2022-09-14 20:48 UTC, adshmh commented on cache/cache_test.go
> +		http.StatusOK, "../samples/apps_limits.json")
Not a blocker, but we should use a `test_data` directory to store all test data files.

2022-09-14 20:48 UTC, adshmh commented on samples/apps_relays.json
> +      "Success": 254673,
We need to update the tests to make sure failed relays are not counted towards the limit

2022-09-14 20:52 UTC, pablocampogo commented on cache/cache_test.go
> +		http.StatusOK, "../samples/apps_limits.json")
I'll do that on other PR, it changes many things

2022-09-15 15:55 UTC, adshmh approved these changes
LGTM. Thanks!

2022-09-15 15:56 UTC, merged