T-15231 Add new logs for rate limit
pokt-foundation/rate-limiter pull request #25
Opened 2022-10-21 20:52 UTC by ricantar

Added logs:
- When an app surpass the daily limit for first time, and every time it triggers the rate-limit after that.
- When it fails to create the router (as error)
- When it fails to set the Cache (as error)
- When it fails to get the counter from the relay-meter (as error)
- When it fails to store the cache (as error)

2022-10-22 00:08 UTC, pablocampogo requested changes
Also run `go mod tidy` too please

2022-10-22 00:08 UTC, pablocampogo commented on main.go
> +			logError("Cache refresh failed", err)
Some of this error can be the same from many requests, please add a way to differentiate them from the cache pkg, using `fmt.Errof` or something like that

2022-10-24 17:45 UTC, ricantar commented on main.go
> +			logError("Cache refresh failed", err)
Change done.

2022-10-25 15:07 UTC, pablocampogo approved these changes

2022-10-25 15:07 UTC, merged